#!/bin/bash

echo ""
echo "    .-''''-."
echo "   /        \\"
echo "  |  🥠🥠🥠  |"
echo "  |          |"
echo "   \\        /"
echo "    '-.__.-'"
echo ""
echo "  🍪 FORTUNE COOKIE 🍪"
echo ""

fortunes=(
    "A beautiful, smart, and loving person will be coming into your life."
    "Your high-minded principles spell success."
    "Your creativity will lead you to success."
    "An unexpected event will bring you fortune."
    "A thrilling time is in your immediate future."
    "Your smile is a treasure to all who know you."
    "Rest is the sweet sauce of labor."
    "A fresh start will put you on your way."
    "You will become infatuated with a beautiful stranger."
    "Your luck is about to change!"
    "A friend is your greatest treasure."
    "Today is a lucky day!"
    "Something you lost will soon be found."
    "Great happiness awaits you."
    "Your hard work will pay off soon!"
    "Expect a pleasant surprise very soon."
    "You are destined for great things!"
    "Adventure awaits you."
    "A smile is your passport into the hearts of others."
    "Your heart is pure and your intentions are good."
    "The fortune you seek is in another cookie."
    "Help! I'm trapped in a fortune cookie factory!"
)

echo "   ${fortunes[$((RANDOM % ${#fortunes[@]}))]}"
echo ""
echo "   - From the Cookie of Wisdom"
echo ""
